version: "3"

services:
    web:
      image: nginx:latest
      ports:
        - "83:80"
      volumes:
        - ./public:/var/www/public/
        - ./docker/nginx:/etc/nginx/conf.d/
      depends_on:
        - db

    php:
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./:/var/www

    db:
      image: mariadb:10.3-bionic
      volumes:
        - ./docker/db/data:/var/lib/mysql:rw
      environment:
        - MYSQL_DATABASE=testteq
        - MYSQL_USER=root_admin
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_PASSWORD=root
      ports:
        - "3303:3306"