version: "3"

services:
    web:
      image: nginx:latest
      ports:
        - "83:80"
      volumes:
        - ./public:/var/www/public/
        - ./docker/nginx:/etc/nginx/conf.d/
      depends_on:
        - php

    php:
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./:/var/www
      depends_on:
        - db

    db:
      image: mariadb:10.3-bionic
      volumes:
        - ./docker/db/data:/var/lib/mysql:rw
      environment:
        - MYSQL_DATABASE=testteq
        - MYSQL_USER=root_admin
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_PASSWORD=root
      ports:
        - "3303:3306"

    rabbitmq:
        image: rabbitmq:3.8.9-management
        env_file:
          - .rabbitmq.env
        ports:
          - "5672:5672"
          - "15672:15672"

    ###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]
    ###< symfony/mailer ###
