<?php

namespace App\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class CompanyAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form): void
    {
        parent::configureFormFields($form); // TODO: Change the autogenerated stub
    }

    protected function configureListFields(ListMapper $list): void
    {
        $list->add('id')
            ->add('name')
            ->add('url')
            ->add('phone')
            ->add('_action', 'actions', [
                'actions' => [
                    'edit' => [],
                    'show' => []
                ]
            ]);
    }

    protected function configureShowFields(ShowMapper $show): void
    {
        $show->add('name')
            ->add('url')
            ->add('address')
            ->add('phone')
            ->add('createdAt');
    }
}